server:
  port: 10000

spring:
  application:
    name: apply
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.106.228:3306/cloud
    username: kk
    password: Outside9991!

  # consul的注册配置
#  cloud:
#    consul:
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}

 #eureka的注册配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: applyT
  client:

    service-url:
      defaultZone: http://127.0.0.1:20000/eureka
    fetch-registry: true
    register-with-eureka: true

